rememberMe: test
reporteya_p: ${REPORTEYA_P}
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${MYSQL_P}
        url: jdbc:mysql://localhost:3306/reporteYa?createDatabaseIfNotExist=true
        username: ${MYSQL_U}
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    mail:
        host: smtp.gmail.com
        password: ${REPORTEYA_P}
        port: 465
        properties:
            mail:
                smpt:
                    auth: true
                    starttls:
                        enable: true
                transport:
                    protocol: smtps
        protocol: smtps
        username: matias.fernandez.17.06@gmail.com
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    servlet:
        multipart:
            max-file-size: 2000KB
            max-request-size: 10000KB
    sql:
        init:
            mode: always
#    web:
#        resources:
#            static-locations: /src/main/resources/static/images
support:
    email: matias.fernandez.17.06@gmail.com