rememberMe: test
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 0800
        url: jdbc:mysql://localhost:3306/reporteYa?createDatabaseIfNotExist=true
        username: root
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    sql:
        init:
            mode: always
